In [3]:
import pandas as pd
df = pd.read_csv("employee_attrition.csv")
df

,Age,Department,Years_At_Company,Salary,Overtime,JobSatisfaction,Attrition
0,29,Sales,12,38,No,3,No
1,23,Finance,12,98,No,1,Yes
2,39,Tech,19,46,No,1,No
3,37,Finance,14,46,No,5,Yes
4,36,Tech,16,90,No,4,Yes
5,30,HR,8,100,Yes,5,No
6,28,Tech,17,51,Yes,5,No
7,27,Tech,0,63,Yes,2,Yes
8,49,HR,3,97,No,1,No
9,24,Tech,17,84,No,5,No
10,23,Sales,8,57,Yes,1,Yes
11,27,HR,20,99,Yes,2,No
12,35,HR,10,55,Yes,1,Yes
13,36,HR,3,69,Yes,5,Yes
14,54,Finance,9,81,No,1,No
15,23,Finance,13,77,Yes,2,Yes
16,34,Tech,5,86,No,4,Yes
17,48,HR,14,96,Yes,1,Yes
18,36,Tech,0,87,No,5,No
19,50,Sales,8,45,No,2,No
20,39,HR,16,61,Yes,5,Yes
21,22,Sales,5,58,Yes,5,No
22,32,Tech,16,38,No,1,Yes
23,49,Finance,3,73,Yes,5,No
24,43,Tech,20,32,Yes,1,No
25,39,Sales,9,100,Yes,4,No
26,31,HR,20,59,Yes,5,Yes
27,35,Tech,16,58,Yes,5,Yes
28,43,HR,19,30,Yes,5,No
29,28,Finance,6,39,No,3,No
30,27,Finance,4,37,No,3,Yes
31,46,Finance,11,59,No,2,Yes
32,28,HR,5,38,Yes,3,No
33,44,Tech,17,34,No,2,Yes
34,44,HR,16,72,Yes,3,No
35,38,HR,0,39,Yes,4,Yes
36,24,Tech,19,95,No,2,No
37,51,Finance,10,60,Yes,3,No
38,29,Finance,15,65,No,4,Yes
39,46,Tech,0,92,No,3,Yes
40,27,HR,3,57,No,1,Yes
41,40,HR,11,99,No,1,Yes
42,45,Finance,9,46,No,4,Yes
43,34,Sales,7,90,No,5,No
44,26,Sales,1,61,Yes,5,Yes
45,24,Sales,7,90,Yes,1,No
46,36,HR,18,82,No,1,Yes
47,40,HR,2,54,Yes,5,Yes
48,27,Finance,2,42,Yes,2,No
49,36,Sales,15,42,Yes,5,No

In [4]:
df.shape

(50, 7)

In [5]:
df.head()

,Age,Department,Years_At_Company,Salary,Overtime,JobSatisfaction,Attrition
0,29,Sales,12,38,No,3,No
1,23,Finance,12,98,No,1,Yes
2,39,Tech,19,46,No,1,No
3,37,Finance,14,46,No,5,Yes
4,36,Tech,16,90,No,4,Yes

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Age               50 non-null     int64
 1   Department        50 non-null     object
 2   Years_At_Company  50 non-null     int64
 3   Salary            50 non-null     int64
 4   Overtime          50 non-null     object
 5   JobSatisfaction   50 non-null     int64
 6   Attrition         50 non-null     object
dtypes: int64(4), object(3)
memory usage: 2.9+ KB

In [7]:
df.describe()

            Age  Years_At_Company      Salary  JobSatisfaction
count  50.00000          50.00000   50.000000        50.000000
mean   35.22000          10.20000   65.340000         3.080000
std     8.78842           6.38557   22.293598         1.626816
min    22.00000           0.00000   30.000000         1.000000
25%    27.25000           5.00000   46.000000         1.250000
50%    35.50000          10.00000   60.500000         3.000000
75%    42.25000          16.00000   86.750000         5.000000
max    54.00000          20.00000  100.000000         5.000000

In [8]:
print("Missing Values:")
print(df.isnull().sum())
print("\n Number of Duplicate Rows:", df.duplicated().sum())

Missing Values:
Age                 0
Department          0
Years_At_Company    0
Salary              0
Overtime            0
JobSatisfaction     0
Attrition           0
dtype: int64

 Number of Duplicate Rows: 0

In [10]:
from sklearn.preprocessing import LabelEncoder
categorical_cols = df.select_dtypes(include=['object'])
lab = LabelEncoder()

for col in categorical_cols:
    df[col] = lab.fit_transform(df[col])

In [11]:
df.head()

,Age,Department,Years_At_Company,Salary,Overtime,JobSatisfaction,Attrition
0,29,2,12,38,0,3,0
1,23,0,12,98,0,1,1
2,39,3,19,46,0,1,0
3,37,0,14,46,0,5,1
4,36,3,16,90,0,4,1

In [12]:
df.dtypes

Age                 int64
Department          int64
Years_At_Company    int64
Salary              int64
Overtime            int64
JobSatisfaction     int64
Attrition           int64
dtype: object

In [13]:
X = df.drop(['Attrition', 'Age', 'Years_At_Company', 'Salary'], axis = 1)
y = df['Attrition']
X = pd.get_dummies(X, columns = ['Department', 'Overtime'], drop_first = True)
display(X.head())
display(y.head())

   JobSatisfaction  Department_1  Department_2  Department_3  Overtime_1
0                3         False          True         False       False
1                1         False         False         False       False
2                1         False         False          True       False
3                5         False         False         False       False
4                4         False         False          True       False

0    0
1    1
2    0
3    1
4    1
Name: Attrition, dtype: int64

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size = 0.2, random_state = 42)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (40, 5)
X_test shape: (10, 5)
y_train shape: (40,)
y_test shape: (10,)

In [15]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators = 100, random_state = 42)
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [16]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average = 'weighted')
recall = recall_score(y_test, y_pred, average = 'weighted')
f1 = f1_score(y_test, y_pred, average  = 'weighted')

print(f"Accuracy: {accuracy:.4f}")
print(f"Precision:  {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-score: {f1:.4f}")

Accuracy: 0.4000
Precision:  0.3810
Recall: 0.4000
F1-score: 0.3750

In [18]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

n_estimators_values = [50, 100, 150]
max_depth_values = [None, 5, 10]
results = []

for n_estimators in n_estimators_values:
     for max_depth in max_depth_values:
         model = RandomForestClassifier(n_estimators = n_estimators, max_depth = max_depth, random_state = 42)
         model.fit(X_train, y_train)
         y_pred = model.predict(X_test)
         
         accuracy = accuracy_score(y_test, y_pred)
         precision = precision_score(y_test, y_pred, average = 'weighted', zero_division = 0)
         recall = recall_score(y_test, y_pred, average = 'weighted', zero_division = 0)
         f1 = f1_score(y_test, y_pred, average = 'weighted', zero_division = 0)

         results.append({
             'max_depth': max_depth,
             'n_estimators': n_estimators,
             'accuracy': accuracy,
             'precision': precision,
             'recall': recall,
             'f1_score': f1
       })
         
results_df = pd.DataFrame(results)
display(results_df)

   max_depth  n_estimators  accuracy  precision  recall  f1_score
0        NaN            50       0.4   0.380952     0.4  0.375000
1        5.0            50       0.5   0.500000     0.5  0.494949
2       10.0            50       0.4   0.380952     0.4  0.375000
3        NaN           100       0.4   0.380952     0.4  0.375000
4        5.0           100       0.4   0.380952     0.4  0.375000
5       10.0           100       0.4   0.380952     0.4  0.375000
6        NaN           150       0.4   0.380952     0.4  0.375000
7        5.0           150       0.3   0.291667     0.3  0.292929
8       10.0           150       0.4   0.380952     0.4  0.375000